- src/client/resources/web/js/chat.js
- src/client/resources/web/js/message_parsing.js
- src/client/resources/web/js/translations.js
- src/client/resources/web/js/util.js
One small non-type change: 
* TS complained that `String.replaceAll()` was a ES2021 feature, so I replaced it with `String.replace()` using a global regex.
> Add types using @ts-check

- src/client/resources/web/js/util.mjs
Was missing the folder prefix which caused errors on Firefox
> Fix img.src path

- build.gradle
Just a little QoL thing as I tend to forget to pull or that I am on a feature branch.
> Warn when building on different branch or behind remote

- src/client/java/dev/creesch/WebInterface.java
- src/client/java/dev/creesch/WebchatClient.java
- src/client/resources/web/js/chat.mjs
- src/client/resources/web/js/message_parsing.mjs
- src/client/resources/web/js/util.mjs
> Use early returns consistently

- src/client/resources/web/js/message_parsing.mjs
- src/test/resources/web/js/message_parsing.test.mjs
> Support raw numbers for component values

- src/client/java/dev/creesch/WebInterface.java
> Normalize multiple spaces from chat input to one

- build.gradle
- gradle.properties
- src/client/java/dev/creesch/WebInterface.java
- src/client/java/dev/creesch/WebchatClient.java
- src/client/java/dev/creesch/model/ChatMessagePayload.java
- src/client/java/dev/creesch/model/HistoryMetaDataPayload.java
- src/client/java/dev/creesch/model/IncomingWebsocketJsonMessage.java
- src/client/java/dev/creesch/model/MessageBuildException.java
- src/client/java/dev/creesch/model/WebsocketJsonMessage.java
- src/client/java/dev/creesch/model/WebsocketMessageBuilder.java
- src/client/java/dev/creesch/storage/ChatMessageRepository.java
- src/client/resources/web/css/main.css
- src/client/resources/web/index.html
- src/client/resources/web/js/chat.mjs
- src/client/resources/web/js/message_types.mjs
This turns out to be a slightly bigger job than I expected because I wanted to make sure the pre-conditions are right.
> History storage and playback

- .github/dependabot.yml
- build.gradle
- dependencies.gradle
- gradle.properties
As the title says, turns out gradle is difficult for depandabot
> Attempted fix at dependabot not seeing dependencies

- src/client/resources/web/index.html
- src/client/resources/web/js/chat.mjs
Fixes #48
- Replaced generic `<div>` elements with more meaningful semantic elements:
- `<main>` for the main container
- `<section>` for chat area and messages
- `<aside>` for the player list
- `<article>` for individual chat messages
Added a few ARIA labels, although I am far from an expert these should cover the basics I think.
> Add aria labels and use semantic elements

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/test-js.yml
On my previous PR I made a formatting mistake and saw "Test" had failed. I think it's best to have this run in a separate lint task.
> Run eslint and prettier in separate workflow

- src/client/java/dev/creesch/WebInterface.java
- src/client/java/dev/creesch/WebchatClient.java
- src/client/java/dev/creesch/config/ModConfigScreen.java
Fixes: #2
Will show the new web address once the server restarts.
> #2 Restart Javalin server when port changes

- src/client/java/dev/creesch/WebInterface.java
> #29 Wait for websocket sessions to close

- src/client/resources/web/css/main.css
- src/client/resources/web/index.html
- src/client/resources/web/js/chat.mjs
- src/client/resources/web/js/managers/tab_list_manager.mjs
Fixes: #42
https://github.com/user-attachments/assets/9227e507-9c39-40ea-b3d7-c602fc3f7670
> #42 Support tab completion of usernames

- src/client/resources/web/css/main.css
- src/client/resources/web/js/chat.mjs
- src/client/resources/web/js/managers/tab_list_manager.mjs
Ramping up for The Big Release
> Small fixes

- src/client/resources/web/css/main.css
- src/client/resources/web/index.html
- src/client/resources/web/js/chat.mjs
- src/client/resources/web/js/messages/message_parsing.mjs
- src/test/resources/web/js/message_parsing.test.mjs
https://github.com/user-attachments/assets/6305cd7f-e1c5-4ae0-b47e-a7fa3f033dab
> Handle click events

- src/client/resources/web/css/main.css
> #95 Fix player head rendering for legacy skins

- src/client/resources/web/css/main.css
- src/client/resources/web/js/messages/message_parsing.mjs
> Click events round two

- src/client/java/dev/creesch/WebInterface.java
- src/client/java/dev/creesch/WebchatClient.java
- src/client/java/dev/creesch/config/ModConfigScreen.java
- src/client/java/dev/creesch/model/WebsocketJsonMessage.java
- src/client/java/dev/creesch/model/WebsocketMessageBuilder.java
- src/client/resources/web/js/chat.mjs
- src/client/resources/web/js/messages/message_types.mjs
Fixes: #21
One awkward point is that the page doesn't reload until a message is sent, which happens once you join a server or singleplayer world.
> Reload webpage on mod version change

- src/client/resources/web/css/main.css
- src/client/resources/web/img/heroicons/bars-3.svg
- src/client/resources/web/img/heroicons/x-mark.svg
- src/client/resources/web/index.html
- src/client/resources/web/js/chat.mjs
- src/client/resources/web/js/managers/player_list.mjs
Fixes: #104
https://github.com/user-attachments/assets/dc40926b-9eef-42a3-abd5-b6a1fcc69e0f
> Add mobile sidebar

- src/client/java/dev/creesch/WebchatClient.java
> Fix crashing when sender is null. Fixes #103

- src/client/java/dev/creesch/WebInterface.java
- src/client/java/dev/creesch/WebchatClient.java
- src/client/java/dev/creesch/storage/ChatMessageRepository.java
Draft as I had less time to work on this than I thought. Still want to do some testing around the error handling I added and possibly reconsider how I am handling some constructors. 
But, it does compile. Runs without crashing the game (that would be ironic). So I am opening the floor for feedback ;)
> Rework error handling to be more graceful

- src/client/java/dev/creesch/model/PlayerListInfoEntry.java
- src/client/java/dev/creesch/model/WebsocketMessageBuilder.java
- src/client/resources/web/js/chat.mjs
- src/client/resources/web/js/managers/direct_message.mjs
- src/client/resources/web/js/managers/player_list.mjs
- src/client/resources/web/js/managers/tab_list_manager.mjs
- src/client/resources/web/js/messages/message_parsing.mjs
- src/client/resources/web/js/messages/message_types.mjs
- src/test/resources/web/js/message_parsing.test.mjs
> Add support for displayName formatting
